### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by samukas81** [tesa-klebeband/RTL8720dn-Deauther#11]
Hallo, können Sie die Firmware-Installation wie bei Ihrem ESP32 über das Internet bereitstellen?  Danke.

**Comment by tesa-klebeband** [comment]
Hi,
Hatte mir das auch schonmal überlegt, aber es gibt noch keine Implementation vom webflasher für den Realtek MCU. Muss mal schauen was sich da machen lässt.

**Comment by samukas81** [comment]
Ok, danke für die Antwort und Glückwunsch zur Arbeit!

**Comment by samukas81** [comment]
Ich erhalte diese Fehlermeldung. Können Sie mir helfen?
![Erro](https://github.com/user-attachments/assets/d282f843-8544-4f56-9363-741915405980)

**Comment by tesa-klebeband** [comment]
Sieht so aus als ob Sie wifi_cust_tx.cpp und den gleichnamigen Header nicht in ihrem Projekt haben. Am besten Sie clonen das projekt über Git oder laden die zip runter.

**Comment by tesa-klebeband** [comment]
Super! Einen schönen Tag noch
