### ISSUE TITLE
5ghz not scanning

### ISSUE THREAD

**Issue by Grzybekrk** [tesa-klebeband/RTL8720dn-Deauther#14]
Hi I know this topic is already closed but Just want to make sure before i will bur black board. I have purple and see only 2.4 what about this note 
Most RTL8720dn devboards have the upload and log serial ports isolated. Make sure to bridge LOG_UART_TX and LP_UART_TX, as well as LOG_UART_RX and LP_UART_RX during uploading.
Is not fixing this issue ??

**Comment by tesa-klebeband** [comment]
Hi, this note is only for uploading on specific boards. If you can upload the code, you can ignore this message. That being said, there was a comment suggesting a fix: "if you have a microscope we are talking about 0.05mm pieces and traces, a good soldering iron and you can uncover it without destroying anything you should make many bridges with 0.01mm wires invert the diplexer and cut various tracks with the risk of destroying everything, considering the cost, it is better to buy a black module (already tested and it works) or a green module (they say it works but I have not tried it) I would like to point out that I have good equipment for SMD and BGA and on the 4th bridge the tracks were destroyed" If you have the tools, you could try, but I think you would be better off to buy a black board. Have a nice day!
