### ISSUE TITLE
I can't find WiFi AP

### ISSUE THREAD

**Issue by ra1n08** [tesa-klebeband/RTL8720dn-Deauther#16]
after I uploaded to my RTL8720DN BW16 (black board w/ type c), I see it work, it debugging a lot in Serial Monitor, I see WiFi Initialized but when I check in WiFi settings on phone, it doesn't show up RTL8720dn-Deauther

**Comment by tesa-klebeband** [comment]
That's indeed weird. Maybe there are too many networks on WiFi channel 1, which the deauther normally uses for its WiFi. You can try changing the current_channel int from 1 to something else and try again. Also, If you have a different board to test this on, try it too.

**Comment by justwibi** [comment]
Any solution about this? I cant see the wifi too
