### ISSUE TITLE
ip: 192.168.1.1 cannot access RTL7820dn

### ISSUE THREAD

**Issue by Nam-Nobi** [tesa-klebeband/RTL8720dn-Deauther#18]
I can't access 192.168.1.1 Please show me how to access your RTL8720dn!

**Comment by tesa-klebeband** [comment]
You are connected to the rtl8720dn right? Can you verify it not working with another device, a phone for example?

**Comment by gpvn07** [comment]
I have tried with all the devices I have: PC, laptop, smartphone all have
the same problem and cannot connect

Vào Th 6, 22 thg 11, 2024 vào lúc 19:30 tesa-klebeband <
***@***.***> đã viết:

**Comment by tesa-klebeband** [comment]
Can you check which IP address the gateway has? Try to type in this ip

**Comment by gpvn07** [comment]
![Capture1](https://github.com/user-attachments/assets/9400f3bb-382d-4364-bf0d-c4859990efbd)
I can't check the port and when I run bw16 the serial monitor reported

**Comment by gpvn07** [comment]
Which ip do I need to try?


Vào Th 6, 22 thg 11, 2024 vào lúc 20:08 tesa-klebeband <
***@***.***> đã viết:

**Comment by gpvn07** [comment]
I can't check the port and when I run bw16 the serial monitor reported
![Capture2](https://github.com/user-attachments/assets/1ad38324-5a75-4e8f-b835-25fef1868fb0)

**Comment by tesa-klebeband** [comment]
Please check which IP is assigned to you and the gateway ip, then post it here.

**Comment by Khoa5555** [comment]
I had the same problem while using it. I unplugged it and plugged it back in but it didn't break the wifi. In the end, I had to reload the code. Can you fix it?

**Comment by Khoa5555** [comment]
I was also using it. I unplugged it and plugged it back in but it didn't deauther the wifi. Finally, I had to reload the code. Can you fix it?

**Comment by tesa-klebeband** [comment]
I have no idea why it isn't working for you. I can only suggest you update the Arduino IDE and try a different device.

**Comment by newer2p** [comment]
Any updates? > I was also using it. I unplugged it and plugged it back in but it didn't deauther the wifi. Finally, I had to reload the code. Can you fix it?
