### ISSUE TITLE
Multiple/Simultaneous Attacks

### ISSUE THREAD

**Issue by transdermal-celebration** [tesa-klebeband/RTL8720dn-Deauther#19]
Is there a way to attack multiple AP's simultaneously? I know this is available in some of the 2.4 frequency De-auth's out there.

**Comment by tesa-klebeband** [comment]
Hi!
Currently not the case, but I agree, it would be nice to do that. If I find some time, I'll do it.
Have a nice day

**Comment by tesa-klebeband** [comment]
Update! I implemented the feature you asked for and also improved the web interface quite a bit.
