### ISSUE TITLE
Can't find 5ghz networks

### ISSUE THREAD

**Issue by ilbossdelfaidate** [tesa-klebeband/RTL8720dn-Deauther#2]
after installing it on the rtl8720dn, the network scan only finds the 2.4ghz even when placing it on the modem

**Comment by tesa-klebeband** [comment]
That's weird. No idea why it isn't picking up these networks, have you modified anything with the board? Maybe the antenna connection is not. Do you have another board to test this with?

**Comment by ilbossdelfaidate** [comment]
I have 2 boards, I'll test with the other one too and let you know
