### ISSUE TITLE
After rescan sometimes cannot makeRedirect

### ISSUE THREAD

**Issue by Rad1ate** [tesa-klebeband/RTL8720dn-Deauther#21]
sometimes web refresh successfully，but sometimes it stops at“192.168.1.1/rescan”

**Comment by tesa-klebeband** [comment]
Yeah, I'm aware that this issue exists. It just didn't bother me as you could just rescan the page. I'll maybe fix it in the future. If you have a solution, fork the repo make your changes and submit a pr.
