### ISSUE TITLE
After the firmware is flashed, there is no 5G hotspot

### ISSUE THREAD

**Issue by LuckyFishGeek** [tesa-klebeband/RTL8720dn-Deauther#6]

**Comment by tesa-klebeband** [comment]
Hi
This means that the device did not find a 5GhZ hotspot. You could try changing the scan timeout which is currently 5000 in the scanNetworks function and see if this helps. Otherwise there might just be no 5G hotspots in your area.

**Comment by tesa-klebeband** [comment]
No problem, let me know if you have any more issues.
