### ISSUE TITLE
Deauth 2.4Ghz and 5Ghz at the same time

### ISSUE THREAD

**Issue by leomacin** [tesa-klebeband/RTL8720dn-Deauther#7]
Could this firmware deauth 2.4GHz and 5GHz at the same time?
is it true dual-band or it could only send packages to either 2.4GHz or 5GHz?

thank you

**Comment by tesa-klebeband** [comment]
Yes, if you use wext_set_channel(WLAN0_NAME, channel); you can change the channel before transmitting the packets to 2.4 or 5GHz. I may make it possible to deauth multiple networks at the same time in this repo.

**Comment by leomacin** [comment]
based on you code, when running deauth, you will lose connection with RTL8720dn-Deauther since the channel will change according to target's channel. is it true?

**Comment by tesa-klebeband** [comment]
Yes, but if you would focus on a single channel, it would be possible to close the WiFi and then reopen it after the channel has been set. This wouldn't work however if I chose to implement the capability to deauth multiple channels.
